services:
  redis:
    image: redis:7
    ports:
      - "${LISTEN_IP:-127.0.0.1}:6379:6379"
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "${LISTEN_IP:-127.0.0.1}:9000:9000"
      - "${LISTEN_IP:-127.0.0.1}:9001:9001"

volumes:
  redis-data:
  minio-data:
